package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class AjouterProduitAdminController implements Initializable {
	@FXML
	private TextField idtxt = new TextField();
	@FXML
	private TextField nomtxt = new TextField();
	@FXML
	private TextField qtxt = new TextField();
	@FXML
	private TextField prixtxtfield = new TextField();
	@FXML
	private Button btnvalider;
	@FXML
	private Button btnretour;
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		idtxt.setText("");
		nomtxt.setText("");
		qtxt.setText("");
		prixtxtfield.setText("");
	}
	
	// Event Listener on Button[#btnvalider].onAction
	@FXML
	public void validationhandler(ActionEvent event) {
		// TODO Autogenerated InvocationTargetException
		try {
			TableServiceController t = new TableServiceController();
			if(nomtxt.getText().equals("") || idtxt.getText().equals("")) {
				Alert error = new Alert(Alert.AlertType.ERROR);
				error.setTitle("Opération échouée");
				error.setContentText("Veuillez insérer un nom et un id.");
				error.setHeaderText(null);
				error.show();
			}
			else {
				Produit produit = new Produit(idtxt.getText(), nomtxt.getText(), Integer.parseInt(qtxt.getText()), t.getSelectedService(), Integer.parseInt(prixtxtfield.getText()) );
				int test = Data.ajouterProduit(produit, TableServiceController.service);
				if (test == 1) {
					initialize(null, null);
					Alert information = new Alert(Alert.AlertType.INFORMATION);
					information.setTitle("Opération réussie");
					information.setContentText("Le produit a été ajouté avec succès");
					information.setHeaderText(null);
					information.show();
					ProduitAdmin2Controller p = new ProduitAdmin2Controller();
					p.initialize(null, null);
				}
				if (test == -1) {
					Alert error = new Alert(Alert.AlertType.ERROR);
					error.setTitle("Opération échouée");
					error.setContentText("L'id saisi figure déjà dans la base de données");
					error.setHeaderText(null);
					error.show();
				}
				if(test == 0) {
					Alert error = new Alert(Alert.AlertType.ERROR);
					error.setTitle("Opération échouée");
					error.setContentText("Problème de connexion");
					error.setHeaderText(null);
					error.show();
				}
			}
			
		}
		catch(NumberFormatException e) {
			Alert error = new Alert(Alert.AlertType.ERROR);
			error.setTitle("Opération échouée");
			error.setContentText("Quantité ou prix invalide");
			error.setHeaderText(null);
			error.show();
			
		}
	}
	
	// Event Listener on Button[#btnretour].onAction
	@FXML
	public void returnhandler(ActionEvent event) {
		// TODO Autogenerated
		initialize(null, null);
		ProduitAdmin2Controller p = new ProduitAdmin2Controller();
		p.initialize(null, null);
		ProduitAdmin2Controller.s.close(SceneAjouterProduitAdmin.principaleWindow);
	}
	
}
