package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class AjouterServiceController implements Initializable {
	@FXML
	private TextField idServiceTextField = new TextField();
	@FXML
	private TextField nomTextFiield = new TextField() ;
	@FXML
	private TextField idGestionnaireTextField = new TextField();
	@FXML
	private Button validationBtn;
	@FXML
	private Button retourBtn;
	
	Admin admin = TableServiceController.admin;
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		idServiceTextField.setText("");
		nomTextFiield.setText("");
		idGestionnaireTextField.setText("");
	}
	
	// Event Listener on Button[#validationBtn].onAction
	@FXML
	public void validationHandler(ActionEvent event) {
		if((idServiceTextField.getText() != null) && !(idServiceTextField.getText().equals(""))) {
			if (idGestionnaireTextField.getText().equals("0000")) {
				Service service = new Service(idServiceTextField.getText(), nomTextFiield.getText(), admin);
				int test = admin.ajouterService(service);
				if (test == -1) {
					Alert error = new Alert(Alert.AlertType.ERROR);
					error.setTitle("Opération échouée");
					error.setContentText("Le service correspondant à l'id saisi figure déjà dans la base de données");
					error.setHeaderText(null);
					error.show();
				}
				else {
					if(test == 1) {
						TableServiceController.items.add(service);
						Alert information = new Alert(Alert.AlertType.INFORMATION);
						information.setTitle("Opération réussie");
						information.setContentText("Le service a été ajouté avec succès");
						information.setHeaderText(null);
						information.show();
						initialize(null, null);
						TableServiceController t = new TableServiceController();
						t.initialize(null, null);
					}
					else {
						Alert error = new Alert(Alert.AlertType.ERROR);
						error.setTitle("Opération échouée");
						error.setContentText("Erreur de la connexion avec la base de données. Veuillez réessayer plus tard.");
						error.setHeaderText(null);
						error.show();
					}
				}
			}
			else {
				Gestionnaire gestionnaire = Data.rechercherGestionnaire(idGestionnaireTextField.getText());
				if (gestionnaire !=null) {
					Service service = new Service(idServiceTextField.getText(), nomTextFiield.getText(), gestionnaire);
					int test = admin.ajouterService(service);
					if(test == 1) {
						TableServiceController.items.add(service);
						Alert information = new Alert(Alert.AlertType.INFORMATION);
						information.setTitle("Opération réussie");
						information.setContentText("Le service a été ajouté avec succès");
						information.setHeaderText(null);
						information.show();
						TableServiceController t = new TableServiceController();
						t.initialize(null, null);
					}
					else {
						if (test == -1) {
							Alert error = new Alert(Alert.AlertType.ERROR);
							error.setTitle("Opération échouée");
							error.setContentText("Le service correspondant à l'id saisi figure déjà dans la base de données");
							error.setHeaderText(null);
							error.show();
						}
						else {
							Alert error = new Alert(Alert.AlertType.ERROR);
							error.setTitle("Opération échouée");
							error.setContentText("Erreur de la connexion avec la base de données. Veuillez réessayer plus tard.");
							error.setHeaderText(null);
							error.show();
						}
					}
				}
				else {
					Alert error = new Alert(Alert.AlertType.ERROR);
					error.setTitle("Opération échouée");
					error.setContentText("Aucun gestionnaire ne correspond à l'id saisi");
					error.setHeaderText(null);
					error.show();
				}
			}
		}
		else {
			Alert error = new Alert(Alert.AlertType.ERROR);
			error.setTitle("Opération échouée");
			error.setContentText("Veuillez saisir un id pour le service");
			error.setHeaderText(null);
			error.show();
		}
		
	}
	
	// Event Listener on Button[#retourBtn].onAction
	@FXML
	public void returnHandler(ActionEvent event) throws IOException {
		// TODO Autogenerated
		TableServiceController.s.close(SceneAjouterService.principaleWindow);
	}
	
}
