package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class Login2Controller {
	@FXML
	private TextField idTextField;
	@FXML
	private TextField nameTextField;
	@FXML
	private PasswordField passwordTextField;
	@FXML
	private Button Signinbtn;
	
	static Gestionnaire gestionnaire = new Gestionnaire();

	@FXML
	public void initialize() {
		idTextField.setText("");
		nameTextField.setText("");
		passwordTextField.setText("");
	}

	// Event Listener on Button[#Signinbtn].onAction
	@FXML
	public Gestionnaire SigningHandler(ActionEvent event) throws IOException  {
		// TODO Autogenerated
		String id = idTextField.getText();
		String name = nameTextField.getText();
		String password = passwordTextField.getText();
		
		if (id.equals("0000")) {
			for (int i=0; i<Data.getGestionnaire().size(); i++) {
				if (id.equals(Data.getGestionnaire().get(i).getIdGestionnaire())) {
					if(name.equals(Data.getGestionnaire().get(i).getNomComplet())) {
						if(password.equals(id+name)) {
							gestionnaire = (Admin)Data.getGestionnaire().get(i);
							AnchorPane root = FXMLLoader.load(getClass().getResource("TableService.fxml"));
							GestionApp.scene.setRoot(root);
							GestionApp.principaleWindow.setWidth(720);
							break;
						}
						else {
							Alert error = new Alert(Alert.AlertType.ERROR);
							error.setTitle("Authentification échouée");
							error.setContentText("Mot de passe incorrect");
							error.setHeaderText(null);
							error.show();
							initialize();
							
						}
					}
					else {
						Alert error = new Alert(Alert.AlertType.ERROR);
						error.setTitle("Authentification échouée");
						error.setContentText("Nom admin incorrect");
						error.setHeaderText(null);
						error.show();
						initialize();
					}
				}
				
			}
			
		}
		else if(Data.rechercherGestionnaire(id)!=null) {
			if(name.equals(Data.rechercherGestionnaire(id).getNomComplet())) {
				if(password.equals(id+name)) {
					gestionnaire = Data.rechercherGestionnaire(id);
					AnchorPane root = FXMLLoader.load(getClass().getResource("AffichageGestionnaire.fxml"));
					GestionApp.scene.setRoot(root);
					GestionApp.principaleWindow.setWidth(720);
				}
				else {
					Alert error = new Alert(Alert.AlertType.ERROR);
					error.setTitle("Authentification échouée");
					error.setContentText("Mot de passe incorrect");
					error.setHeaderText(null);
					error.show();
					initialize();
				}
			}
			else {
				Alert error = new Alert(Alert.AlertType.ERROR);
				error.setTitle("Authentification échouée");
				error.setContentText("Nom gestionnaire incorrect");
				error.setHeaderText(null);
				error.show();
				initialize();
			}
		}
        else{
        	Alert error = new Alert(Alert.AlertType.ERROR);
        	error.setTitle("Authentification échouée");
        	error.setContentText("Aucun gestionnaire ne correspond à l'id saisi");
        	error.setHeaderText(null);
        	error.show();
        	initialize();
        }
		return gestionnaire;
	}

	public Gestionnaire getGestionnaire() {
		return gestionnaire;
	}
	
	public TextField getIdTextField() {
        return idTextField;
    }

}
