package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;


public class ModifierProduitAdminController implements Initializable{
	@FXML
	private TextField NewNameTextField = new TextField();
	@FXML
	private TextField NewQuantityTextField = new TextField();
	@FXML
	private TextField NewServiceTextField = new TextField();
	@FXML
	private TextField prixtxtfield = new TextField();
	@FXML
	private Button ValidationButton;
	@FXML
	private Button ReturnButton;
	
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		NewNameTextField.setText("");
		NewQuantityTextField.setText("");
		NewServiceTextField.setText("");
		prixtxtfield.setText("");
		
	}

	// Event Listener on Button[#ValidationButton].onAction
	@FXML
	public void ValidationHandler(ActionEvent event) {
		// TODO Autogenerated
		String name =NewNameTextField.getText();
		String quant = NewQuantityTextField.getText();
		String service = NewServiceTextField.getText();
		String prix = prixtxtfield.getText();
		if(name.equals("") && quant.equals("") && service.equals("") && prix.equals("")){
			Alert error = new Alert(Alert.AlertType.ERROR);
			error.setTitle("Opération échouée");
			error.setContentText("Veuillez saisir des information");
			error.setHeaderText(null);
			error.show();
			
		}
		else {
			String name2 = name.equals("")? ProduitAdmin2Controller.p.getNom(): name;
			String service2 = service.equals("")? ProduitAdmin2Controller.p.getService().getIdService(): service;
			String quant2 = quant.equals("")? String.valueOf(ProduitAdmin2Controller.p.getQuantite()): quant;
			String prix2 = prix.equals("")? String.valueOf(ProduitAdmin2Controller.p.getPrix()):prix;
			Service service3 = Data.rechercherService(service2);
			if (service3 == null) {
				Alert error = new Alert(Alert.AlertType.ERROR);
				error.setTitle("Opération échouée");
				error.setContentText("Service introuvable.");
				error.setHeaderText(null);
				error.show();
			}
			else {
				try {
					Produit p = new Produit(ProduitAdmin2Controller.p.getIdProduit(), name2, Integer.parseInt(quant2), service3, Integer.parseInt(prix2));
					if (service2.equals(ProduitAdmin2Controller.p.getService().getIdService())) {
						Data.modifierProduit(ProduitAdmin2Controller.p, p);
						ProduitAdmin2Controller.items.add(p);
						ProduitAdmin2Controller.items.remove(ProduitAdmin2Controller.p);
						Alert information = new Alert(Alert.AlertType.INFORMATION);
						information.setTitle("Opération réussie");
						information.setContentText("Le produit a été modifié avec succès");
						information.setHeaderText(null);
						information.show();
						initialize(null, null);
						ProduitAdmin2Controller pa = new ProduitAdmin2Controller();
						pa.initialize(null, null);
					}
					else {
						Data.modifierProduit(ProduitAdmin2Controller.p, p);
						Alert information = new Alert(Alert.AlertType.INFORMATION);
						information.setTitle("Opération réussie");
						information.setContentText("Le produit a été modifié avec succès");
						information.setHeaderText(null);
						information.show();
						initialize(null, null);
						ProduitAdmin2Controller pa = new ProduitAdmin2Controller();
						pa.initialize(null, null);
					}
					
				}
				catch(NumberFormatException e) {
					Alert error = new Alert(Alert.AlertType.ERROR);
					error.setTitle("Opération échouée");
					error.setContentText("Quantité ou prix invalide");
					error.setHeaderText(null);
					error.show();
				}
				
			}
			
		}
		
	}
	
	// Event Listener on Button[#ReturnButton].onAction
	@FXML
	public void ReturnHandler(ActionEvent event) {
		// TODO Autogenerated
		//ProduitAdmin2Controller.s2.close(SceneModifierProduit.principaleWindow);
		initialize(null, null);
		ProduitAdmin2Controller p = new ProduitAdmin2Controller();
		p.initialize(null, null);
		ProduitAdmin2Controller.s2.close(SceneModifierProduitAdmin.principaleWindow);
	}
	
}
